### ISSUE TITLE
No recompilation on change

### ISSUE THREAD

**Issue by Buom01** [devmattrick/parcel-plugin-nunjucks#14]
Hi,
I expect issues with this package.
When a file was modified, absolutely nothing happend;

Current behaviour
I edit a .njk file -> I refresh the browser -> I see that the edition isn't propagated

Expected behaviour
I edit a .njk file -> I refresh the browser -> I see, like for .html file, the updated file

Note that  `options: { noCache: true }` or restarting parcel does not even works to update output.
I need to force the update by remove `.cache` and `dist` folder.

Do I have miss to do anythings ?

Thanks

**Comment by chocolateboy** [comment]
Hard to say without more details or a test repo, but the version with dependency tracking (1.1.0) wasn't released to NPM until February (2019-02-16).
