### ISSUE TITLE
npm version is not up to date with latest merge

### ISSUE THREAD

**Issue by sdegueldre** [devmattrick/parcel-plugin-nunjucks#15]
This means all changes introduced [here](https://github.com/devmattrick/parcel-plugin-nunjucks/pull/11) are unavailable by using `npm install parcel-plugin-nunjucks`, including dependency management. Installing from the github using `npm install devmattrick/parcel-plugin-nunjucks` solves this.

**Comment by devmattrick** [comment]
Published under `parcel-plugin-nunjucks@1.1.0`. Sorry about that!

**Comment by sdegueldre** [comment]
Fantastic, thank you!
