### ISSUE TITLE
Can't get the plugin to work

### ISSUE THREAD

**Issue by baglio** [devmattrick/parcel-plugin-nunjucks#16]
Upon installing the plugin, creating a *nunjucks.config.js* and executing `parcel src/html/index.njk`, Parcel can not resolve the entry:

```
Cannot resolve entry "/Users/myuser/myfolder/Parcel-playground/src/html/index.njk" from "/Users/myuser/myfolder/Parcel-playground/src/html"
```
Is there something I'm missing?

**Comment by trickydisco78** [comment]
Same here. Can't get this to work

**Comment by lepture** [comment]
You need to configure `root` in `nunjucks.config.js`
