### ISSUE TITLE
Referencing an HTML file in an anchor will break the compilation

### ISSUE THREAD

**Issue by andy0130tw** [devmattrick/parcel-plugin-nunjucks#17]
Suppose that I have two files: `1.njk` and `2.njk`. The content of `2.njk` does not matter, and let `1.njk` contain an anchor to it.

```html
<a href="2.html">...</a>
```

This will fail to resolve with the following error:

```
...: 🚨  /.../1.njk: ENOENT: no such file or directory, open '/.../2.html'
```

That's because that `2.html` is compiled from `2.njk` in fact. However, I cannot simply name them with the `html` extension, since they need to be explicitly in `njk` extension for compilation. A workaround is to point the anchor to `2.njk`, but I think it is weird for an HTML to link to a template.

**Comment by chocolateboy** [comment]
The `.njk` extension is required by Parcel (v1 at least). Otherwise, we could allow `2.njk.html`. Once #2 lands, you can use `2.html.njk`.
