### ISSUE TITLE
Documentation or some kind of examples

### ISSUE THREAD

**Issue by rv-earagao** [devmattrick/parcel-plugin-nunjucks#4]
Hi, 

First of all thanks for your contribution, but, since Parceljs is a new thing, the most of the people doesn't know it very well.

It would be pretty nice to have some kind of example of how to use it... I just installed and it doesn't work as I expected, it just not compile nunjucks templates at all. I believe that's something I'm doing wrong, but it's impossible to know if there's no documentation at all.

**Comment by devmattrick** [comment]
There's really nothing to document as there's no configuration. The only requirement this plugin has is that you use the `.njk` extension.

**Comment by rv-earagao** [comment]
Oh...
So in that case we have a bug.

I have a `src/pages/home/index.njk` which is using a `src/layouts/default.njk` with a `extends` clause.

But it seems that isn't working... It doesn't raise any error, but the generated html isn't parsing nunjucks code. I have the following output in the browser:

`{% extends "src/layouts/default.njk" %} {% block content %} test {% endblock %}`

**Comment by devmattrick** [comment]
Hmm...it looks like nunjucks doesn't like it when it is configured to use a directory, but you reference a file from a different directory. I'll have to look into it.

**Comment by gregorybolkenstijn** [comment]
+1
