### ISSUE TITLE
Provide nunjucks configurations

### ISSUE THREAD

**Issue by Javiani** [devmattrick/parcel-plugin-nunjucks#5]
Hi, 

How can I add global variables to my templates? How can I add new filters if there's no way to configure that?

**Comment by wind930** [comment]
@Javiani  You can pay attention to my previous submission 
https://github.com/wind930/parcel-plugin-nunjucks

A temporary scheme before the merge request

1. NPM I --save-dev wind930/parcel-plugin-nunjucks

2. create nunjucks.config.js

3. write your global variables in nunjucks.config.js

4. use your global variables in templates

5. fun to play
