### ISSUE TITLE
Using Nunjucks inheritance

### ISSUE THREAD

**Issue by reinoute** [devmattrick/parcel-plugin-nunjucks#7]
Is there any way I can get Nunjucks inheritance (`extends`) to work?

It looks like the plugin uses Nunjucks `renderString` to parse the template (and not the FileSystemLoader).

If it's not possible, is there an alternative way to achieve having 'master' templates such as the example below?

````
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        {% block header %}{% endblock %} 
    </head>
    <body>
        {% block content %}{% endblock %} 
    </body>
</html>
````

**Comment by chocolateboy** [comment]
Probably an instance of [this bug](https://github.com/devmattrick/parcel-plugin-nunjucks/issues/4#issuecomment-368194626) (which should be split or renamed). Inheritance with `extend` currently only works if referenced files are in the same directory. Ditto `macro` and `include`.
